export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const INSERTING_DATA = 'INSERTING_DATA';
export const INSERTING_DATA_SUCCESS = 'INSERTING_DATA_SUCCESS';
export const INSERTING_DATA_FAILURE = 'INSERTING_DATA_FAILURE';
export const DELETING_DATA = 'DELETING_DATA';
export const GET_NAME = 'GET_NAME';

